# Physical parameters
physical_config:
  kn: 0.00000001
  time_dimension: 1
  space_dimension: 1
  velocity_dimension: 1
  t_range: [0.0, 0.1]
  x_range: [0.0, 1.0]
  v_range: [-1.0, 1.0] 

# Dataset parameters
dataset_config:
  interior_samples: 1024
  boundary_samples: 512
  initial_samples: 1024

# Model parameters
model_config:
  device_ids: [0]
  lr: 0.001
  stage_num: 500
  decay_rate: 0.96
  iterations: 10000  
  neural_network_type: "FCNet" # type 1 - "ResNet"; type 2 - "FCNet"  
  units_rho: [128, 128, 128, 128]
  units_g: [256, 256, 256, 256]
  num_vquads: 30
  regularizers: [1.0, 1.0, 10.0, 10.0] 

  