# Physical parameters
physical_config:
  time_dimension: 1
  space_dimension: 1
  t_range: [0.0, 1.0]
  x_range: [-1.0, 1.0]
  viscosity: 0.01


# Dataset parameters
dataset_config:
  interior_samples: 256
  initial_samples: 128
  boundary_samples: 64
  
# Model parameters
model_config:
  device_ids: [0]
  lr: 0.001
  stage_num: 500
  decay_rate: 0.96
  iterations: 10000
  neural_network_type: "ResNet" # type 1 - "ResNet"; type 2 - "FCNet"
  units_u:  [80, 80, 80, 80, 80, 80] 
  regularizers: [1.0, 1.0, 1.0] # weights: [bgk_eqn,  bc, ic] 
 
  
