# Physical parameters
physical_config:
  kn: 0.00001
  time_dimension: 1
  space_dimension: 1
  velocity_dimension: 1
  uq_dimension: 20
  num_path: 1000
  z_range: [-1.0, 1.0]
  t_range: [0.0, 0.1]
  x_range: [0.0, 1.0]
  v_range: [0.0, 1.0] 

# Dataset parameters
dataset_config:
  interior_samples: 1024
  boundary_samples: 512
  initial_samples: 256

# Model parameters
model_config:
  device_ids: [1] # [1, 2, 5]
  lr: 0.001
  stage_num: 400
  decay_rate: 0.96
  iterations: 20000 
  neural_network_type: "FCNet"   
  units_rho: [64, 128, 256, 256, 128, 64]
  units_r: [128, 256, 512, 512, 256, 128]
  units_j: [128, 256, 512, 512, 256, 128]
  num_vquads: 30
  regularizers: [1.0, 1.0, 1.0, 1.0, 10.0, 1.0, 10.0] # parity * 2, claw, constraint, boundary, initial(rho, f) 

  