# Physical domain parameters
dataset_config:
  interior_samples: 512
  initial_samples: 512
  boundary_samples: 128
  t_range: [0.005, 0.05]
  x_range: [-0.5, 0.5]
  v_range: [-10.0, 10.0]
  
# Model parameters
model_config:
  kn: 0.01
  nvquad: 64
  neural_network_type: "ResNet" # 1. ResNet; 2. FCNet
  units_f: [128, 128, 128, 128, 128, 128] # ResNet: must be even and length > 4
  units_rho: [96, 96, 96, 96, 96, 96] # ResNet: must be even and length > 4
  units_u: [96, 96, 96, 96, 96, 96] # ResNet: must be even and length > 4
  units_T: [96, 96, 96, 96, 96, 96] # ResNet: must be even and length > 4
  regularizers: [1.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 1.0, 1.0, 1.0, 10.0, 1.0, 10.0, 10.0] # weights: [bgk_eqn, conservation * 3, relaxation * 3, bc * 3, ic * 4] 
  initializer: "glorot_uniform"
  lr: 0.00005
  stage_num: 250
  decay_rate: 1.0
  iterations: 5000
