# Physical parameters
physical_config:
  time_dimension: 1
  space_dimension: 1
  velocity_dimension: 1
  t_range: [0.0, 0.1]
  x_range: [0.0, 1.0]
  v_range: [0.0, 1.0] 

# Dataset parameters
dataset_config:
  interior_samples: 512
  boundary_samples: 1024
  initial_samples: 512

# Model parameters
model_config:
  device_ids: [0]
  lr: 0.001
  stage_num: 1000
  decay_rate: 0.96
  iterations: 10000 
  neural_network_type: "FCNet" # type 1 - "ResNet"; type 2 - "FCNet"  
  units_rho: [128, 128, 128, 128]
  units_r: [256, 256, 256, 256]
  units_j: [256, 256, 256, 256]
  kn: 0.001
  num_vquads: 30
  regularizers: [1.0, 1.0, 1.0, 1.0, 10.0, 1.0, 10.0] # parity * 2, claw, constraint, boundary, initial(rho, f) 

  